<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>DaqLink.App</RootNamespace>
    <AssemblyName>DaqLink</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DaqLink.Core\DaqLink.Core.csproj" />
  </ItemGroup>

</Project>
